:고성능 파이썬 패키지(정의)
:pip install numpy (설치법)
:https://blog.naver.com/reisei11/221762330326(Python모듈,패키지,pip
:https://numpy.org/(공식사이트)
:빠르고 효율.벡터.브로드캐스팅 연산 지원. 반복문 작성 필요 없이 빠른 연산제공. 배열 데이터를 디스크에 읽거나 쓰기 가능. 파일 저장 가능(장점)
:ndarray객체 만들기(-->대규모 데이터 n차원 배열 담기O)
arange()
array([])
:크기 설정
ndarray.size(원소개수)
ndarray.shape(행렬 모양)
ndarray.ndim(행렬의 축)
reshape()
:type(파이썬 내장함수=Numpy내부의 자료형)
NumPy: numpy.array.dtype
파이썬: type()
* Numpy의 원소는 같은 데이터타입을 가져야함.

:특수행렬(Numpy에서 제공하는 행렬)
-단위행렬
-0 행렬
-1 행렬

:브로드캐스트연산(ndarray객체에 직접 상수연산 적용O)

:슬라이스와 인덱싱
https://d3s0tskafalll9.cloudfront.net/media/original_images/f-11-5.1.png

:난수지원(random)

print(np.random.random())   # 0에서 1사이의 실수형 난수 하나를 생성합니다. 

print(np.random.randint(0,10))   # 0~9 사이 1개 정수형 난수 하나를 생성합니다. 

print(np.random.choice([0,1,2,3,4,5,6,7,8,9]))   # 리스트에 주어진 값 중 하나를 랜덤하게 골라줍니다.

#아래 2가지는 기능면에서 동일합니다. 원소의 순서를 임의로 뒤바꾸어 줍니다. 

print(np.random.permutation(10))   
print(np.random.permutation([0,1,2,3,4,5,6,7,8,9]))

#np.transpose는 행렬의 축을 어떻게 변환해 줄지 임의로 지정해 줄 수 있는 일반적인 행렬 전치 함수입니다. 
#np.transpose(A, (2,1,0)) 은 A.T와 정확히 같습니다.

B = np.transpose(A, (2,0,1))
print(A)             # A는 (2,3,4)의 shape를 가진 행렬입니다. 
print(B)             # B는 A의 3, 1, 2번째 축을 자신의 1, 2, 3번째 축으로 가진 행렬입니다.
print(B.shape)  # B는 (4,2,3)의 shape를 가진 행렬입니다.

:전치 행렬(행과 열 맞바꾸기, 행렬의 축을 서로 바뀌기)
arr.T
np.transpose

In [1]:
import numpy as np

# 아래 A와 B는 결과적으로 같은 ndarray 객체를 생성합니다. 
A = np.arange(5)
B = np.array([0,1,2,3,4])  # 파이썬 리스트를 numpy ndarray로 변환

# 하지만 C는 좀 다를 것입니다. 
C = np.array([0,1,2,3,'4'])

# D도 A, B와 같은 결과를 내겠지만, B의 방법을 권합니다. 
D = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))

print(A)
print(type(A))
print(B)
print(type(B))
print(C)
print(type(C))
print(D)
print(type(D))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>
['0' '1' '2' '3' '4']
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
A = np.arange(10).reshape(2,5)   # 길이 10의 1차원 행렬을 2X5 2차원 행렬로 바꿔봅니다.

print(A.shape)
print(A.ndim)
print(A.size)

(2, 5)
2
10


In [3]:
A= np.arange(6).reshape(2,3)
print(A)
print(A.dtype)
print(type(A))

B = np.array([0,1,2,3,4,5])  
print(B)
print(B.dtype)
print(type(B))

C = np.array([0,1,2,3,'4',5])
print(C)
print(C.dtype)
print(type(C))

D = np.array([0,1,2,3,[4,5],6])  # 이런 ndarray도 만들어질까요?
print(D)
print(D.dtype)
print(type(D))

[[0 1 2]
 [3 4 5]]
int64
<class 'numpy.ndarray'>
[0 1 2 3 4 5]
int64
<class 'numpy.ndarray'>
['0' '1' '2' '3' '4' '5']
<U21
<class 'numpy.ndarray'>
[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  app.launch_new_instance()


In [7]:
# 단위행렬
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# 1행렬
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# 0 행렬
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
A = np.arange(24).reshape(2,3,4)
print(A)               # A는 (2,3,4)의 shape를 가진 행렬입니다. 
print(A.T)            # 이것은 A의 전치행렬입니다. 
print(A.T.shape) # A의 전치행렬은 (4,3,2)의 shape를 가진 행렬입니다.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)
