# Numpy - 2

numpy는 수치 연산과 관련된 모듈로, 숫자형 데이터를 보다 세분화된 형태로 저장합니다.
- 크게 정수/실수/복소수/Boolean형으로 구분합니다.
- 데이터형 뒤에는 비트수를 표기합니다. 

https://numpy.org/devdocs/user/basics.types.html

인스턴스 변수 `dtype`에는 데이터 타입이 저장돼 있습니다. `int32`는 정수 (`integer`) 값을 저장할 수 있는 32 bits 자료형이라는 뜻입니다. 숫자가 커질 수록 더욱 큰 수를 저장할 수 있는 반면 더 많은 저장 공간을 필요로 합니다. 

In [ ]:
import numpy as np
a = np.arange(4)
print(a.dtype)

int64


데이터 타입을 변경할 때는 `astype` 메서드를 사용합니다. `int8`은 `int32` 보다 적은 숫자를 저장할 수 있겠죠?

In [ ]:
a = a.astype('int8')
print(a.dtype)

a[0] = 127
a[1] = 128
print(a)

int8
[ 127 -128    2    3]


In [ ]:
# 8bit로 설정하면 a[0]=200 a[1]-200이렇게 안된다는거죠?


`uint8`은 부호없는 정수를 저장하며 `int8`보다 조금 더(2배) 큰 숫자를 저장할 수 있습니다. 

In [ ]:
a = a.astype('uint8')
print(a.dtype)

a[0] = 255
a[1] = 256
print(a)

uint8
[255   0   2   3]


## 넘파이의 연산
넘파이의 사칙연산은 전체 데이터에 적용되는데, 이를 브로드 캐스팅 (broadcasting)이라고 합니다. 
### 사칙연산
곱셈 연산이 `ndarray`에 저장된 모든 데이터에 적용됐음을 알 수 있습니다. 

In [ ]:
import numpy as np

a = np.arange(4)
print(a)
print( a * 3 )

[0 1 2 3]
[0 3 6 9]


곱셈 뿐만 아니라 덧셈/뺄셈/나눗셈에 대해서도 모두 동작합니다.

In [ ]:
print( a + 10 )
print( a - 10 )
print( a / 3 )

[10 11 12 13]
[-10  -9  -8  -7]
[0.         0.33333333 0.66666667 1.        ]


ndarray와의 연산

In [ ]:
a = np.arange(4)
b = np.arange(2, 6)
print(a+b)

[2 4 6 8]


Q. 중간고사 성적의 분산을 출력하라
- v𝑎𝑟(𝑋)=𝐸((𝑋−𝜇)2)

<img src="https://i.ibb.co/SfVzf0Z/image.png" width="250" style="float:left" />

In [23]:
점수 = np.array([  30, 25, 66, 23, 44, 23   ]).reshape(2, 3)
점수.var()

242.47222222222226

Q. 중간/기말고사 성적의 분산을 출력하라

In [24]:
점수 = np.array([  30, 25, 66, 23, 44, 23   ]).reshape(2, 3)

In [25]:
점수.var(axis=1)

array([333.55555556,  98.        ])

특정 위치에 접근할 수 있다면, 값을 수정할 수도 있습니다.

In [ ]:
a[0] = 30
a

array([30,  1,  2,  3])

In [ ]:
a[  : 2] = 20
a

array([20, 20,  2,  3])

In [ ]:
a[[0, 3]] = 0

In [ ]:
a

array([ 0, 20,  2,  0])

### 비교연산
넘파이는 크다/작다/같다/다르다 등의 비교 연산을 지원합니다. 연산의 결과는 Boolean형 데이터 타입이며, 사칙연산과 같이 모든 데이터에 비교 연산이 적용됩니다. 연산의 결괏값은 `ndarray` 입니다. 

In [ ]:
a = np.arange(5)
결과 = a > 3 
print(결과)

[False False False False  True]


<img src="https://i.ibb.co/HTpkqfW/1.png" width="600" style="float:left" />

불린형 데이터 타입이 저장된 `ndarray`를 사용해서 값을 filtering할 수 있습니다. 조건을 충족하는 4가 출력됩니다. 

In [ ]:
a = np.arange(5)
조건 = a > 3 
조건

array([False, False, False, False,  True])

In [ ]:
a[    [ False, False, False, True, True ]   ]

array([3, 4])

In [ ]:
a[ 조건  ]

array([4])

위 코드는 간단하기 때문에 조건 비교와 인덱싱을 한 번에 표현할 수 있습니다. 

In [ ]:
조건 = a > 3 
a[ 조건  ]

array([4])

In [ ]:
a[       a > 3    ] 

array([4])

`np.where` 구문을 사용하면 데이터를 쉽게 변경할 수 있습니다. 

In [26]:
# 조건이 참이면 10, 그렇지 않으면 20으로 채움
np.where(a > 3, 10, 20)

array([10, 10, 10])

In [27]:
# 조건이 참이면 원본값 그대로, 그렇지 않으면 a에 10을 더함
np.where(a > 3, a, a+10)

array([10, 20, 30])

비교할 조건이 다수라면 `&` 기호로 조건을 구분하며, 각각의 조건 역시 괄호 `( )`로 구분해야 합니다. 

In [28]:
np.where((a > 3) & (a < 5), a, a+10)

array([20, 30, 40])

Q. LG전자의 종가 데이터가 ndarray 형태로 저장되어 있다. LG 전자의 주가가 85000원 보다 작을 때의 가격을 출력하라.

In [ ]:
lge = np.array([93000, 82400, 99100, 81000, 72300])

In [ ]:
cond = lge < 85000
lge[ cond ]

array([82400, 81000, 72300])

In [ ]:
lge[    lge < 85000 ]

array([82400, 81000, 72300])

Q. LG 전자의 주가가 85000원 이하로 떨어진 횟수는?

In [ ]:
len(  lge[    lge < 85000 ]  )

3

Q. 종가가 80000원 이상  90000원 미만인 값을 출력하라

In [ ]:
cond1 = lge >= 80000
cond2 = lge < 90000

In [ ]:
cond1 & cond2

array([False,  True, False,  True, False])

In [ ]:
lge[    cond1 & cond2      ]

array([82400, 81000])

In [ ]:
lge[    cond1 | cond2      ]

array([93000, 82400, 99100, 81000, 72300])

In [ ]:
lge[  ~ cond1 ]

array([72300])

In [ ]:
lge[(lge >= 80000) & (lge < 90000)] 

array([82400, 81000])

ndarray??  
`리스트, 딕셔너리, 튜플`

In [ ]:
# 넘파이 모듈 : 여러 클래스, 함수, 데이터 (자료구조)

In [ ]:
a = np.array([10, 20 , 30])
type(a)

numpy.ndarray

In [ ]:
a.shape

(3,)

In [ ]:
a.ndim

1

In [ ]:
a.base

`조건 슬라이싱은  파이썬 리스트로는 불가능 하고 넘파이에서만 가능한가요?`  

네. 이는 numpy 에서 지원하는 문법입니다



다음 코드가 에러난다면?
```
!pip install numpy
import numpy as np
!pip install image
from PIL import Image
img = Image.open("image/0.png")
img = img.convert('L')
img
```


`pillow보다 opencv로 이미지처리하는게 바로 numpy로 바꾸어주어서 더 좋은가요?`

영상처리에 전문적인 모듈이 opencv입니다. 적절한 모듈을 사용하면 됩니다

open() 함수로 이미지나 다른 확장자 파일을 갖고오는것은 파이썬 실행 파일이 저장된 위치를 기본 저장공간?으로 정의 하나요?

In [ ]:
f = open("/content/aaa/data.txt", "w")
f.write("ㅋㅋㅋㅋㅋㅋ")
f.close()

In [ ]:
f = open("data.txt", "r")
lines = f.readlines()
print(lines)
f.close()

['ㅋㅋㅋㅋㅋㅋ']


근데 img하니까 강아지 사진 나오는데, print(img)하면 안 나오는데 정상이죠? print(img) 하니까 <PIL.Image.Image image mode=L size=345x510 at 0x120201DF0> 가 나와요
