<a href="https://colab.research.google.com/github/qsdcfd/TIL/blob/TIL/Study__221/Numpy_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

### 1.1. Numpy Array creation

In [6]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [2]:
# 파이썬 리스트 선언
data = [1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [4]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [[1,2], [3,4]]
data2

[[1, 2], [3, 4]]

In [9]:


# 파이썬 list를 numpy array로 변환합니다.
arr =np.array(data)
# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
arr

array([1, 2, 3, 4, 5])

In [8]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.
arr2

array([[1, 2],
       [3, 4]])

In [11]:
# 0부터 9까지 숫자를 자동으로 생성한 array
#np.array(list(range(10)))
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 10부터 99까지 숫자를 자동으로 생성한 array
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### 1.2. Reshaping array

In [14]:
# 3 x 3 행렬을 만들어봅시다.
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# reshape을 이용하여 만들어봅시다.
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# row vector를 column vector로
np.arange(6).reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
# 펼치기
x.reshape(-1, )

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.3. Concatenation of arrays

In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1 + arr2 = ?
arr1 + arr2
# arr1와 arr2를 합칩니다
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [21]:
# stacking vertically
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# stacking horizontally
np.hstack([arr1,arr2])

array([1, 2, 3, 4, 5, 6])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [24]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [25]:
# 리스트로 더하기 연산해보기
L = [1,2,3]
L2 = [4,5,6]
L + L2

[1, 2, 3, 4, 5, 6]

In [26]:
#  vector addition
v1 + v2

array([5, 7, 9])

In [27]:
#  vector subtraction
v1-v2

array([-3, -3, -3])

In [28]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [29]:
# (not vector operation) elementwise division
v1/v2

array([0.25, 0.4 , 0.5 ])

In [30]:
# dot product
v1 @ v2

32

### 1.5. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [31]:
arr1 = np.array([1,2,3])

In [32]:
arr2 = np.array([[-1,-1,-1],
                 [1,1,1]])
arr2.shape 

(2, 3)

In [33]:
# 2개의 array를 더해보면?
arr1 + arr2 # 2->2->3(v)

array([[0, 1, 2],
       [2, 3, 4]])

In [34]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[-1, -2, -3],
       [ 1,  2,  3]])

- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [35]:
# f = lambda x : 1/x
arr1 = np.array([1., 2., 3.])
print(1 / arr1)

[1.         0.5        0.33333333]


In [36]:
# f = lambda x : x + 2
arr1 = arr1 +2
arr1

array([3., 4., 5.])

### 1.6. Indexing


In [ ]:
arr1 = np.arange(10)

In [37]:
# 첫번째 원소
arr1[0]

3.0

In [38]:
# 마지막 원소
arr1[-1]

5.0

In [39]:
# 앞에서부터 원소 3개 slicing
arr[:3]

array([1, 2, 3])

In [40]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
# arr2의 2row, 3column 원소 = 7
arr2[1][2]
arr2[1,2]

7

In [43]:
# arr2의 세번째 column [3, 7, 11]
arr2[0,2]
arr2[1,2]
arr2[2,2]
arr2[:,2]

array([ 3,  7, 11])

In [44]:
# arr2의 두번째 row
arr2[0:2, 0:2]

array([[1, 2],
       [5, 6]])

## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions 

In [45]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
mat1 = np.random.randn(5,3)
mat1

array([[-1.61131402, -0.32932463, -0.96780569],
       [-1.04595115, -1.33803069,  0.7785728 ],
       [-0.60272802, -0.39344687, -1.45002982],
       [ 0.51787084,  2.061645  ,  1.08489648],
       [-0.57888785,  1.48597866,  1.44614198]])

In [46]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[1.61131402, 0.32932463, 0.96780569],
       [1.04595115, 1.33803069, 0.7785728 ],
       [0.60272802, 0.39344687, 1.45002982],
       [0.51787084, 2.061645  , 1.08489648],
       [0.57888785, 1.48597866, 1.44614198]])

In [47]:
# mat1 제곱하기
np.square(mat1)

array([[2.59633288, 0.10845471, 0.93664785],
       [1.0940138 , 1.79032613, 0.60617561],
       [0.36328107, 0.15480044, 2.10258649],
       [0.26819021, 4.25038009, 1.17700038],
       [0.33511115, 2.20813259, 2.09132664]])

In [48]:
# mat1의 제곱근 구하기
np.sqrt(mat1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[       nan,        nan,        nan],
       [       nan,        nan, 0.88236772],
       [       nan,        nan,        nan],
       [0.71963244, 1.43584296, 1.04158364],
       [       nan, 1.21900725, 1.20255644]])

In [51]:
# linear algebra functions
vec = np.array([1, 2 ,3])

# 1. norm
np.linalg.norm(vec) #Vector L2 norm

# 2. eigenvalue
mat1 = np.array([[1,2],
           [3,4]])

np.linalg.eig(mat1)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

### 2.2. Aggregation functions 

In [53]:
mat2 = np.random.rand(3, 2)
mat2

array([[0.30807481, 0.72571265],
       [0.17226228, 0.75425152],
       [0.44613091, 0.20957241]])

In [54]:
# Summation
np.sum(mat2)
np.sum(mat2, axis=1)
np.sum(mat2, axis=0)

array([0.926468  , 1.68953659])

In [55]:
# mean
np.mean(mat2)
np.mean(mat2, axis=0)


array([0.30882267, 0.56317886])

In [56]:
# std
np.std(mat2)

0.23184476853776334

In [57]:
# min, max
np.min(mat2, axis=0)
np.max(mat2, axis=1)

array([0.72571265, 0.75425152, 0.44613091])

In [58]:
# 최소값이 있는 Index
np.argmin(mat2, axis=0)
np.argmax(mat2, axis=1)

array([1, 1, 0])

In [59]:
# 최대값이 있는 Index
np.argmax(mat2, axis=1)

array([1, 1, 0])

In [61]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)
mat2

array([[0.30807481, 0.72571265],
       [0.17226228, 0.75425152],
       [0.44613091, 0.20957241]])

In [65]:
## 내림차순 정렬
np.sort(mat2, axis = 0)[::-1]

array([[0.44613091, 0.75425152],
       [0.30807481, 0.72571265],
       [0.17226228, 0.20957241]])

In [64]:
# index를 정렬
np.argsort(mat2, axis=0)

array([[1, 2],
       [0, 0],
       [2, 1]])

## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [66]:
np.random.seed(0)

def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

In [67]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 100, 1000000)
big_array

array([45, 48, 65, ..., 93, 62, 19])

In [68]:
%timeit reverse_num(big_array)

1 loop, best of 5: 2.64 s per loop


In [69]:
%timeit 1.0 / big_array

100 loops, best of 5: 3.01 ms per loop
